#ifndef GAMETXT_H
#define GAMETXT_H

extern const char *Messages[];
extern const char *DungeonMessages[];
extern const char *Armor[];
extern const char *Melee[];
extern const char *Ranged[];
extern const char *Status[];
extern const char *Gender[];
extern const char MenuText[];
extern const char MenuChoices[];
extern const char *MarkerPos[];
extern const char MenuPrompt[];
extern const short NPCText[];
extern const short NPCName[];
extern const char *NPC[];
extern const char NPCFunction[];
extern const char *Arena[];
extern const char *MonsterName[];
extern const char EnemyToTile[];
extern const char EnemyPower[];
extern const char EnemyHPBase[];
extern const char EnemyStartX[];
extern const char EnemyStartY[];
extern const char TrollStartX[];
extern const char DungeonStartX[];
extern const char DungeonStartY[];
extern const char WaterStartX[];
extern const char WaterStartY[];
extern const char PirateStartX[];
extern const char PirateStartY[];
extern const char EnemyTraits[];
extern const char gold_range[];
extern const char enemy_damage[];
extern const char *SpellName[];
extern const char *Wind[];
extern const char AltWall[];
extern const char AltWallSecret[];

#define ENEMY_RANGED 0x80
#define ENEMY_POISON 0x40
#define ENEMY_RESPAWN 0x20
#define ENEMY_STRONG 0x10
#define ENEMY_GRAPPLE 0x08
#define ENEMY_TELEPORT 0x04
#define ENEMY_FIRE 0x02
#define ENEMY_INCORPORAL 0x01

#define RAY_SPELL       0x01
#define SWAP_SPELL      0x02
#define SUN_SPELL       0x04
#define HEAL_SPELL      0x08
#define TELEPORT_SPELL       0x10
#define ZAP_SPELL       0x20



#define OUTDOOR_MENU 0
#define TOWN_MENU 1
#define VENDOR_MENU 2
#define HERO_COMBAT_MENU 3
#define DRAGON_COMBAT_MENU 4
#define SPELL_MENU 5
#define DUNGEON_MENU 6
#define ITEM_MENU 7

#define ARMOR_NONE 0
#define ARMOR_LEATHER 1
#define ARMOR_CHAIN 2
#define ARMOR_PLATE 3
#define ARMOR_M_PLATE 4
#define ARMOR_DRAGON 5

#define MELEE_STAFF 0
#define MELEE_MACE 1
#define MELEE_AXE 2
#define MELEE_SWORD 3
#define MELEE_M_SWORD 4
#define MELEE_S_HAMMER 5

#define RANGED_NONE 0
#define RANGED_SLING 1
#define RANGED_BOW 2
#define RANGED_M_BOW 3
#define RANGED_S_HAMMER 4

#define DWARF_TILE_NUMBER 56
#define FIRE_BEETLE_TILE_NUMBER 62
#define DARKLING_TILE_NUMBER 63
#define SHADOW_RAT_TILE_NUMBER 64
#define DRAGON_TILE_NUMBER 60
#define COMBAT_HERO_TILE_NUMBER 65
#define MISSILE_TILE_NUMBER 67
#define SKELETON_TILE_NUMBER 68
#define TROLL_TILE_NUMBER 109
#define TROLL_ENEMY_NUMBER 0
#define SALAMANDER_ENEMY_NUMBER 17
#define SLIME_ENEMY_NUMBER 30
#define PIRATE_ENEMY_NUMBER 16
#define SEA_SERPENT_ENEMY_NUMBER 23
#define GOBLIN_TILE_NUMBER 63
#define SHADOW_ORB_TILE_NUMBER 71
#define OGRE_TILE_NUMBER 69
#define HEAD_TILE_NUMBER 72
#define GIANT_TILE_NUMBER 73
#define DEATH_BUG_TILE_NUMBER 62
#define DARK_DRAKE_TILE_NUMBER 84
#define NIGHT_WISP_TILE_NUMBER 91
#define GLOOM_VIPER_TILE_NUMBER 92
#define UNSEELIE_TILE_NUMBER 63
#define TITAN_TILE_NUMBER 108
#define PIRATE_TILE_NUMBER 83
#define SALAMANDER_TILE_NUMBER 84
#define DEMON_GUARD_TILE_NUMBER 85
#define EARTH_SHADE_TILE_NUMBER 88
#define WATER_SHADE_TILE_NUMBER 87
#define FIRE_SHADE_TILE_NUMBER 86
#define AIR_SHADE_TILE_NUMBER 22
#define SEA_SERPENT_TILE_NUMBER 92
#define WATER_WIGHT_TILE_NUMBER 93
#define GIANT_SQUID_TILE_NUMBER 94
#define ZOMBIE_TILE_NUMBER 97
#define DIRE_SPIDER_TILE_NUMBER 98
#define MINOTAUR_TILE_NUMBER 99
#define HELL_RABBIT_TILE_NUMBER 100
#define SLIME_TILE_NUMBER 101
#define ROPER_TILE_NUMBER 102
#define VAMPIRE_BAT_TILE_NUMBER 103
#define GHOST_TILE_NUMBER 93
#define MUMMY_TILE_NUMBER 104
#define ICE_DEVIL_TILE_NUMBER 17
#define AMOEBA_TILE_NUMBER 105
#define DEMON_TILE_NUMBER 85
#define LICH_TILE_NUMBER 106
#define DRAGON_MONSTER_TILE_NUMBER 107

#define DUNGEON_MONSTER_OFFSET 26


#define STATUS__QUEEN_AVALINE 0
#define STATUS__A_MYSTERIOUS_VOICE_SAYS 1
#define STATUS__LOOT_THIS_CHEST 2
#define STATUS__WARDEN_GREGORY 3
#define STATUS__SERVER_XAVIER 4
#define STATUS__EXPLORER_CONSTANCE 5
#define STATUS__FENRICK 6
#define STATUS__THE_ORACLE_SAYS 7
#define STATUS__CURE_POTION_VENDOR 8
#define STATUS__BEATRICE_THE_GUARD 9
#define STATUS__ROXANNE_THE_MAID 10
#define STATUS__GROUNDSMAN_HECTOR 11
#define STATUS__MAZINNA_THE_HERMIT 12
#define STATUS__LETA_THE_GARDENER 13
#define STATUS__DRINK_FROM_THE_FOUNTAIN 14
#define STATUS__YOU_HEAR_WATER_DRINK 15
#define STATUS__JAYLAN_THE_SMITH 16
#define STATUS__CAPTAIN_RODRICK 17
#define STATUS__FIRST_MATE_WILLIE 18
#define STATUS__GRETA_THE_GOBLIN 19
#define STATUS__EX_PIRATE_FLETA 20
#define STATUS__GUARD_MADDOX 21
#define STATUS__GARRICK_THE_WIZARD 22
#define STATUS__MARDEN_THE_ELDER 23
#define STATUS__FAY_THE_TRAVELER 24
#define STATUS__WIXA_THE_ALCHEMIST 25
#define STATUS__BAXTON_THE_WIZARD 26
#define STATUS__DID_YOU_BRING_ME_ACORNS 27
#define STATUS__MAGE_MAXIMILIAN 28
#define STATUS__TRAIN_WITH_ME 29
#define STATUS__CLANELDER_DURON 30
#define STATUS__GOLDWINE_THE_BARD_SAYS 31
#define STATUS__THE_PRISONER_SAYS 32
#define STATUS__THE_OGRE_SAYS 33
#define STATUS__THE_CREATURE_SAYS 34
#define STATUS__WIK_THE_GRUNT 35
#define STATUS__OVERSEER_THAL 36
#define STATUS__OVERSEER_YARGOT 37
#define STATUS__GRUNT_BALUZAG 38
#define STATUS__GRUNT_ERUK 39
#define STATUS__DESERTER_TRAGUT 40
#define STATUS__GRUNT_BOKUR 41
#define STATUS__SAMUEL_THE_MEDIC 42
#define STATUS__GIVE_HOW_MANY_POTIONS 43
#define STATUS__MAYORINEXILE_JUL 44
#define STATUS__WATCHMAN_BERNARD 45
#define STATUS__EDWIN_THE_WAYFARER 46
#define STATUS__THEOBALD_THE_SAGE 47
#define STATUS__RANULF_THE_WIZARD 48
#define STATUS__RANGER_JULIANA 49
#define STATUS__HIGH_PRIESTESS_ADA 50
#define STATUS__ELDER_SAPPHIRE 51
#define STATUS__ALDERNEY_THE_SEER 52
#define STATUS__AVIL_THE_WARRIOR 53
#define STATUS__RAY_THE_APPRENTICE 54
#define STATUS__SAM_THE_ADVENTURER 55
#define STATUS__AUDREY_THE_CONVICT 56
#define STATUS__BARNABY_THE_PIRATE 57
#define STATUS__JOHN_THE_INSURGENT 58
#define STATUS__CLAN_ELDER_THORINA 59
#define STATUS__DOROTHY_THE_TIPSY 60
#define STATUS__STEWARD_ROWLAND 61
#define STATUS__MARSHAL_CATHERINE 62
#define STATUS__SOLDIER_LEONARD 63
#define STATUS__SAILOR_TOBIAS 64
#define STATUS__GYMARA_THE_SAILOR 65
#define STATUS__DEMON_GUARD 66
#define STATUS__UMFREY_THE_SPY 67
#define STATUS__MAGE_MARY_ANN 68
#define STATUS__HILDA_THE_EXPLORER 69
#define STATUS__PROSPECTOR_DIVANA 70
#define STATUS__BRONK_THE_SERVANT 71
#define STATUS__YOU_SAY 72
#define STATUS__THANA_THE_USURPER 73
#define STATUS__THE_BARTENDER_SAYS 74
#define STATUS__KING_RUFUS 75
#define STATUS__IDA_THE_JESTER 76
#define STATUS__GROCER 77
#define STATUS__ROBIN_THE_BARFLY 78
#define STATUS__MAYOR_WADE 79
#define STATUS__CLAN_CHIEF_TRAVOK 80
#define STATUS__RUTGAR_THE_MINER 81
#define STATUS__BORIN_THE_MINER 82
#define STATUS__AMBER_THE_JUVENILE 83
#define STATUS__SOLDIER_GADORA 84
#define STATUS__VISTRA_THE_SMITH 85
#define STATUS__EVA_THE_FIGHTER 86
#define STATUS__RANDALL_THE_LONER 87
#define STATUS__ALISTAIR_THE_ELDER 88
#define STATUS__GUARD 89
#define STATUS__EZIN_THE_SAGE 90
#define STATUS__MYSTERIOUS_HERMIT 91
#define STATUS__FULK_THE_DEPARTED 92
#define STATUS__DALIN_THE_DWARF 93
#define STATUS__SIR_DEVON 94
#define STATUS__SWORDSMAN_PENGENAR 95
#define STATUS__BAERN_THE_SMITH 96
#define STATUS__SLING_VENDOR 97
#define STATUS__BOW_VENDOR 98
#define STATUS__AXE_VENDOR 99
#define STATUS__MACE_VENDOR 100
#define STATUS__SWORD_VENDOR 101
#define STATUS__CHAINMAIL_VENDOR 102
#define STATUS__LEATHER_VENDOR 103
#define STATUS__PLATEMAIL_VENDOR 104
#define STATUS__HEALER 105
#define STATUS__HEALING_POTION_VENDOR 106
#define STATUS__GROVE_WARDEN_GLYNN 107
#define STATUS__MAYOR_BALDRIC 108
#define STATUS__DECKHAND_JORDAN 109
#define STATUS__FRIAR_HENRY 110
#define STATUS__CAPTAIN_SABINA 111
#define STATUS__MILLIE_THE_GOSSIP 112
#define STATUS__FARMER_WILLIAM 113
#define STATUS__ISABEL_THE_RECLUSE 114
#define STATUS__FORWIN_THE_WIZARD 115
#define STATUS__ROLF_THE_MIGHTY 116
#define STATUS__GILES_THE_RANGER 117
#define STATUS__NESTA_THE_RANGER 118
#define STATUS__NIGEL_THE_LOST 119
#define STATUS__TERRIC_THE_SAGE 120
#define STATUS__ELENA_THE_YOUTH 121
#define STATUS__ORACLE_GUARD 122
#define STATUS__SHIP_VENDOR 123
#define STATUS__BARTENDER 124
#define STATUS__THE_MERCHANT_SAYS 125
#define STATUS__THE_HEALER_SAYS 126
#define STATUS__FREE_HEALING 127
#define STATUS__ASCEND_TO_NEXT_LEVEL 128
#define STATUS__DESCEND_TO_PREVIOUS_LEVEL 129
#define STATUS__ASCEND_OR_DESCEND 130
#define STATUS__ACTIONS 131
#define STATUS__SPELLS 132
#define STATUS__ITEMS 133
#define STATUS__REST_AND_SAVE_YOUR_GAME 134
#define STATUS__REST_HERE 135
#define STATUS__VICTORY 136
#define STATUS__MSWORD_VENDOR 137
#define STATUS__MBOW_VENDOR 138
#define STATUS__FORGEGURU_RISWYNN 139
#define STATUS__CLAN_ELDER_DURON 140
#define STATUS__GOLDWINE_THE_BARD 141
#define STATUS__PLATE_VENDOR 142
#define STATUS__OGRE_CHIEFTAIN_DAK 143
#define STATUS__GUARDSMAN_TAYLOR 144
#define MESSAGE__RETURN_WHEN_YOUR_DEEDS_ARE_MORE_NOTEWORTHY 145
#define MESSAGE__ENTERING_STONEHEART 146
#define MESSAGE__ENTERING_WATERS 147
#define MESSAGE__ENTERING_OAK 148
#define MESSAGE__ENTERING_CASTLE_AVALINA 149
#define MESSAGE__ENTERING_SPIRETOP 150
#define MESSAGE__EXITING_TO_THE_HIGH_SEA 151
#define MESSAGE__ENTERING_THANAS_HOLD 152
#define MESSAGE__ENTERING_FREEHAVEN 153
#define MESSAGE__ENTERING_KEEP_OF_SHADOW 154
#define MESSAGE__THE_DISGUISE_WEARS_OFF 155
#define MESSAGE__YOU_FIND_FIRE_ACORNS 156
#define MESSAGE__YOU_FIND_SPIRIT_STONE 157
#define MESSAGE__ENTERING_ACADIA 158
#define MESSAGE__YES_NO 159
#define MESSAGE__EXITING_TO_FARADUR 160
#define MESSAGE__THE_RUINS_OF_DUSKGROVE 161
#define MESSAGE__GO_AND_EXPERIENCE_MORE 162
#define MESSAGE__YOU_CANT_GO_THAT_WAY 163
#define MESSAGE__DUNGEON_MENU 164
#define MESSAGE__DUNGEON_MENU_UP 165
#define MESSAGE__DUNGEON_MENU_DOWN 166
#define MESSAGE__DUNGEON_MENU_UP_DOWN 167
#define MESSAGE__OUTDOOR_MENU 168
#define MESSAGE__HERO_COMBAT_MENU 169
#define MESSAGE__DRAGON_COMBAT_MENU 170
#define MESSAGE__TOWN_MENU 171
#define MESSAGE__SWAPPED_GRAPPLE_BROKEN 172
#define MESSAGE__NOT_ENOUGH_SPELL_POINTS 173
#define MESSAGE__NOTHING_MUCH_HAPPENS 174
#define MESSAGE__PARTY_HEALED 175
#define MESSAGE__CURED 176
#define MESSAGE__WHICH_DIRECTION 177
#define MESSAGE__ALREADY_HEALED 178
#define MESSAGE__SAVED 179
#define MESSAGE__RESTED 180
#define MESSAGE__SWAPPED 181
#define MESSAGE__NOT_HERE 182
#define MESSAGE__YOU_CHANGE_FORM 183
#define MESSAGE__NO_RANGED_WEAPON 184
#define MESSAGE__NOTHING_TO_USE 185
#define MESSAGE__HOMING_GEM_INVOKED 186
#define MESSAGE__FEY_DRAGON_IS_NOT_HERE 187
#define MESSAGE__MOVED 188
#define MESSAGE__RUFUS_TALK 189
#define MESSAGE__EZIN_THE_SAGE_TALK 190
#define MESSAGE__DALIN_THE_DWARF_TALK 191
#define MESSAGE__GUARD_TALK 192
#define MESSAGE__IDA_THE_JESTER_TALK 193
#define MESSAGE__SWORDSMAN_PENGENAR_TALK 194
#define MESSAGE__ROBIN_THE_BARFLY_TALK 195
#define MESSAGE__RANDALL_THE_LONER_TALK 196
#define MESSAGE__ALISTAIR_THE_ELDER_TALK 197
#define MESSAGE__GUARDSMAN_TAYLOR_TALK 198
#define MESSAGE__EVA_THE_FIGHTER_TALK 199
#define MESSAGE__ACADIA_BARTENDER_TALK 200
#define MESSAGE__MAYOR_WADE_TALK 201
#define MESSAGE__CASTLE_BARTENDER_TALK 202
#define MESSAGE__MYSTERIOUS_HERMIT_TALK 203
#define MESSAGE__BAERN_THE_SMITH_TALK 204
#define MESSAGE__CLAN_CHIEF_TRAVOK_TALK 205
#define MESSAGE__STONEHEART_BARTENDER_TALK 206
#define MESSAGE__AMBER_THE_JUVENILE_TALK 207
#define MESSAGE__VISTRA_THE_SMITH_TALK 208
#define MESSAGE__RUTGAR_THE_MINER_TALK 209
#define MESSAGE__BORIN_THE_MINER_TALK 210
#define MESSAGE__SOLDIER_GADORA_TALK 211
#define MESSAGE__FORGEGURU_RISWYNN_TALK 212
#define MESSAGE__GROVE_WARDEN_GLYNN_TALK 213
#define MESSAGE__ORACLE_GUARD_TALK 214
#define MESSAGE__GILES_THE_RANGER_TALK 215
#define MESSAGE__NESTA_THE_RANGER_TALK 216
#define MESSAGE__NIGEL_THE_LOST_TALK 217
#define MESSAGE__ELENA_THE_YOUTH_TALK 218
#define MESSAGE__TERRIC_THE_SAGE_TALK 219
#define MESSAGE__OAK_BARTENDER_TALK 220
#define MESSAGE__MAYOR_BALDRIC_TALK 221
#define MESSAGE__WATERS_BARTENDER_TALK 222
#define MESSAGE__DECKHAND_JORDAN_TALK 223
#define MESSAGE__FRIAR_HENRY_TALK 224
#define MESSAGE__CAPTAIN_SABINA_TALK 225
#define MESSAGE__ISABEL_THE_RECLUSE_TALK 226
#define MESSAGE__FARMER_WILLIAM_TALK 227
#define MESSAGE__FORWIN_THE_WIZARD_TALK 228
#define MESSAGE__MILLIE_THE_GOSSIP_TALK 229
#define MESSAGE__WARDEN_GREGORY_TALK 230
#define MESSAGE__SERVER_XAVIER_TALK 231
#define MESSAGE__EXPLORER_CONSTANCE_TALK 232
#define MESSAGE__FENRICK_TALK 233
#define MESSAGE__CASTLE_ORACLE_TALK 234
#define MESSAGE__BEATRICE_THE_GUARD_TALK 235
#define MESSAGE__ROXANNE_THE_MAID_TALK 236
#define MESSAGE__GROUNDSMAN_HECTOR_TALK 237
#define MESSAGE__MAZINNA_THE_HERMIT_TALK 238
#define MESSAGE__LETA_THE_GARDENER_TALK 239
#define MESSAGE__FREEHAVEN_BARTENDER_TALK 240
#define MESSAGE__JAYLAN_THE_SMITH_TALK 241
#define MESSAGE__CAPTAIN_RODRICK_TALK 242
#define MESSAGE__FIRST_MATE_WILLIE_TALK 243
#define MESSAGE__GRETA_THE_GOBLIN_TALK 244
#define MESSAGE__EX_PIRATE_FLETA_TALK 245
#define MESSAGE__GUARD_MADDOX_TALK 246
#define MESSAGE__GARRICK_THE_WIZARD_TALK 247
#define MESSAGE__MARDEN_THE_ELDER_TALK 248
#define MESSAGE__FAY_THE_TRAVELER_TALK 249
#define MESSAGE__WIXA_THE_ALCHEMIST_TALK 250
#define MESSAGE__BAXTON_THE_WIZARD_TALK 251
#define MESSAGE__MAGE_MAXIMILIAN_TALK 252
#define MESSAGE__CLAN_ELDER_DURON_TALK 253
#define MESSAGE__GOLDWINE_THE_BARD_TALK 254
#define MESSAGE__WIK_THE_GRUNT_TALK 255
#define MESSAGE__OGRE_CHIEFTAIN_DAK_TALK 256
#define MESSAGE__OVERSEER_THAL_TALK 257
#define MESSAGE__OVERSEER_YARGOT_TALK 258
#define MESSAGE__GRUNT_BALUZAG_TALK 259
#define MESSAGE__GRUNT_ERUK_TALK 260
#define MESSAGE__DESERTER_TRAGUT_TALK 261
#define MESSAGE__GRUNT_BOKUR_TALK 262
#define MESSAGE__DUSKGROVE_BARTENDER_TALK 263
#define MESSAGE__SAMUEL_THE_MEDIC_TALK 264
#define MESSAGE__MAYORINEXILE_JUL_TALK 265
#define MESSAGE__WATCHMAN_BERNARD_TALK 266
#define MESSAGE__SPIRETOP_BARTENDER_TALK 267
#define MESSAGE__EDWIN_THE_WAYFARER_TALK 268
#define MESSAGE__THEOBALD_THE_SAGE_TALK 269
#define MESSAGE__RANULF_THE_WIZARD_TALK 270
#define MESSAGE__RANGER_JULIANA_TALK 271
#define MESSAGE__HIGH_PRIESTESS_ADA_TALK 272
#define MESSAGE__ELDER_SAPPHIRE_TALK 273
#define MESSAGE__ALDERNEY_THE_SEER_TALK 274
#define MESSAGE__AVIL_THE_WARRIOR_TALK 275
#define MESSAGE__CLAN_ELDER_THORINA_TALK 276
#define MESSAGE__BARNABY_THE_PIRATE_TALK 277
#define MESSAGE__AUDREY_THE_CONVICT_TALK 278
#define MESSAGE__JOHN_THE_INSURGENT_TALK 279
#define MESSAGE__DOROTHY_THE_TIPSY_TALK 280
#define MESSAGE__STEWARD_ROWLAND_TALK 281
#define MESSAGE__MARSHAL_CATHERINE_TALK 282
#define MESSAGE__SOLDIER_LEONARD_TALK 283
#define MESSAGE__OAK_ORACLE_TALK 284
#define MESSAGE__SAILOR_TOBIAS_TALK 285
#define MESSAGE__GYMARA_THE_SAILOR_TALK 286
#define MESSAGE__THANAS_HOLD_BARTENDER_TALK 287
#define MESSAGE__DEMON_GUARD_TALK 288
#define MESSAGE__UMFREY_THE_SPY_TALK 289
#define MESSAGE__MAGE_MARY_ANN_TALK 290
#define MESSAGE__HILDA_THE_EXPLORER_TALK 291
#define MESSAGE__PROSPECTOR_DIVANA_TALK 292
#define MESSAGE__BRONK_THE_SERVANT_TALK 293
#define MESSAGE__OPEN_SESAME 294
#define MESSAGE__GO_AWAY_FORCE_FIELD 295
#define MESSAGE__FOOL_YOU_CANT_HARM_ME 296
#define MESSAGE__FULK_THE_DEPARTED 297
#define MESSAGE__SIR_DEVON_TALK 298
#define MESSAGE__RAY_THE_APPRENTICE_TALK 299
#define MESSAGE__SAM_THE_ADVENTURER_TALK 300
#define MESSAGE__ROLF_THE_MIGHTY_TALK 301
#define MESSAGE__GIVE_SPIRIT_HAMMER 302
#define MESSAGE__THANK_YOU_FOR_YOUR_HELP 303
#define MESSAGE__ALREADY_HAVE_DRAGON_ARMOR 304
#define MESSAGE__YOU_ARE_NOW_GREATER 305
#define MESSAGE__A_HUMAN_ATTACK 306
#define MESSAGE__ANOTHER_TIME_PERHAPS 307
#define MESSAGE__THANA_SECONDARY_DIALOG 308
#define MESSAGE__FIND_FULK 309
#define MESSAGE__THANK_YOU_COME_AGAIN 310
#define MESSAGE__USE_THIS_ONLY_WHEN_YOUR_PERIL_IS_MOST_DIRE 311
#define MESSAGE__ALDERNEY_THE_SEER_TALK_2 312
#define MESSAGE__GIVE_DRAGON_ARMOR 313
#define MESSAGE__YOU_HAVE_ENOUGH_ALREADY 314
#define MESSAGE__GO_AWAY 315
#define MESSAGE__YOU_HAVE_NO_NEED_OF_IT 316
#define MESSAGE__ALREADY_HAVE_SPIRIT_HAMMER 317
#define MESSAGE__WHY_NOT 318
#define MESSAGE__ANMARBOKFILOT 319
#define MESSAGE__FIND_THE_OTHER_TRAINERS 320
#define MESSAGE__YOU_DONT_HAVE_ENOUGH 321
#define MESSAGE__WHERE 322
#define MESSAGE__SPIRIT_STONE_CLUE 323
#define MESSAGE__NO_ONE_IS_HERE 324
#define MESSAGE__POISONED 325
#define MESSAGE__OUT_OF_FOOD 326
#define MESSAGE__NO_ENEMY_THERE 327
#define MESSAGE__MISSED 328
#define MESSAGE__PASS 329
#define MESSAGE__THE_DRAGON_IS_HIT 330
#define MESSAGE__FEY_DRAGON_DISSIPATES 331
#define MESSAGE__YOU_HAVE_BEEN_RESTORED 332
#define MESSAGE__HEALED 333
#define MESSAGE__YOU_LEARN_A_NEW_SPELL 334
#define MESSAGE__ITS_DARK 335

#define DUNGEON__SOME_WALLS_ARE_FAKE        0
#define DUNGEON__DRAFTY_CLUES               1
#define DUNGEON__INNER_MAZE                 2
#define DUNGEON__SECRETS_SECRETS_SEC        3
#define DUNGEON__WATERY_ROULETTE            4
#define DUNGEON__CENTER_YOURSELF_TO_SOAR    5
#define DUNGEON__DEADLY_CORNERS             6
#define DUNGEON__WINDY_ESCAPE               7
#define DUNGEON__FOLLOW_THE_BREADCRUMBS     8
#define DUNGEON__FORTUNE_AND_FALLS          9
#define DUNGEON__LAYERS_OF_DECEPTION        10
#define DUNGEON__ONE_TWO_THREE_FOUR_FIVE    11
#define DUNGEON__DONT_RISE_TOO_SOON         12
#define DUNGEON__FAST_WAY_OR_SLOW_WAY       13
#define DUNGEON__A_WINDFALL_LIFTS_YOU_UP    14
#define DUNGEON__AVOID_A_PATH_TO_NOWHERE    15
#define DUNGEON__PATHS_OF_DARKNESS          16
#define DUNGEON__PITS_AND_LADDERS           17
#define DUNGEON__DROP_TO_ADVANCE            18
#define DUNGEON__CORRIDOR_OF_DOOM           19
#define DUNGEON__CAVERN_OF_WONDERS          20
#define DUNGEON__MINING_FOR_SECRETS         21
#define DUNGEON__EASIER_THAN_IT_SEEMS       22
#define DUNGEON__THE_LONG_MARCH             23
#define DUNGEON__MAGIC_WILL_TAKE_YOU_FAR    24
#define DUNGEON__PILLAR_OF_RICHES           25
#define DUNGEON__FIND_THE_ENERGY_SOURCE     26
#define DUNGEON__HIDDEN_MAZE                27
#define DUNGEON__REWARDS_AND_DESPAIR        28
#define DUNGEON__WATCH_YOUR_STEP            29
#define DUNGEON__WINDY_STASH                30
#define DUNGEON__BOONS_AND_ESCAPE           31

#define QUEEN_AVALINE 0
#define KING_RUFUS 1
#define EZIN_THE_SAGE 2
#define DALIN_THE_DWARF 3
#define GUARD 4
#define IDA_THE_JESTER 5
#define SWORDSMAN_PENGENAR 6
#define GROCER 7
#define ROBIN_THE_BARFLY 8
#define RANDALL_THE_LONER 9
#define ALISTAIR_THE_ELDER 10
#define GUARDSMAN_TAYLOR 11
#define EVA_THE_FIGHTER 12
#define SLING_VENDOR 13
#define LEATHER_VENDOR 14
#define ACADIA_BARTENDER 15
#define MAYOR_WADE 16
#define CASTLE_BARTENDER 17
#define HEALER 18
#define MYSTERIOUS_HERMIT 19
#define BAERN_THE_SMITH 20
#define CLAN_CHIEF_TRAVOK 21
#define STONEHEART_BARTENDER 22
#define AMBER_THE_JUVENILE 23
#define VISTRA_THE_SMITH 24
#define RUTGAR_THE_MINER 25
#define BORIN_THE_MINER 26
#define SOLDIER_GADORA 27
#define PLATE_VENDOR 28
#define FORGEGURU_RISWYNN 29
#define AXE_VENDOR 30
#define MACE_VENDOR 31
#define GROVE_WARDEN_GLYNN 32
#define BOW_VENDOR 33
#define ORACLE_GUARD 34
#define GILES_THE_RANGER 35
#define NESTA_THE_RANGER 36
#define NIGEL_THE_LOST 37
#define ELENA_THE_YOUTH 38
#define TERRIC_THE_SAGE 39
#define OAK_BARTENDER 40
#define HEALING_POTION_VENDOR 41
#define MAYOR_BALDRIC 42
#define WATERS_BARTENDER 43
#define DECKHAND_JORDAN 44
#define FRIAR_HENRY 45
#define SHIP_VENDOR 46
#define CAPTAIN_SABINA 47
#define ISABEL_THE_RECLUSE 48
#define FARMER_WILLIAM 49
#define SWORD_VENDOR 50
#define CHAINMAIL_VENDOR 51
#define FORWIN_THE_WIZARD 52
#define MILLIE_THE_GOSSIP 53
#define WARDEN_GREGORY 54
#define SERVER_XAVIER 55
#define EXPLORER_CONSTANCE 56
#define FENRICK 57
#define CASTLE_ORACLE 58
#define CURE_POTION_VENDOR 59
#define BEATRICE_THE_GUARD 60
#define ROXANNE_THE_MAID 61
#define GROUNDSMAN_HECTOR 62
#define MAZINNA_THE_HERMIT 63
#define LETA_THE_GARDENER 64
#define FREEHAVEN_BARTENDER 65
#define JAYLAN_THE_SMITH 66
#define CAPTAIN_RODRICK 67
#define FIRST_MATE_WILLIE 68
#define GRETA_THE_GOBLIN 69
#define EX_PIRATE_FLETA 70
#define GUARD_MADDOX 71
#define GARRICK_THE_WIZARD 72
#define MARDEN_THE_ELDER 73
#define FAY_THE_TRAVELER 74
#define WIXA_THE_ALCHEMIST 75
#define BAXTON_THE_WIZARD 76
#define MAGE_MAXIMILIAN 77
#define CLAN_ELDER_DURON 78
#define GOLDWINE_THE_BARD 79
#define WIK_THE_GRUNT 80
#define OGRE_CHIEFTAIN_DAK 81
#define OVERSEER_THAL 82
#define OVERSEER_YARGOT 83
#define GRUNT_BALUZAG 84
#define GRUNT_ERUK 85
#define DESERTER_TRAGUT 86
#define GRUNT_BOKUR 87
#define DUSKGROVE_BARTENDER 88
#define SAMUEL_THE_MEDIC 89
#define MAYORINEXILE_JUL 90
#define WATCHMAN_BERNARD 91
#define SPIRETOP_BARTENDER 92
#define EDWIN_THE_WAYFARER 93
#define THEOBALD_THE_SAGE 94
#define RANULF_THE_WIZARD 95
#define RANGER_JULIANA 96
#define HIGH_PRIESTESS_ADA 97
#define ELDER_SAPPHIRE 98
#define ALDERNEY_THE_SEER 99
#define AVIL_THE_WARRIOR 100
#define CLAN_ELDER_THORINA 101
#define BARNABY_THE_PIRATE 102
#define AUDREY_THE_CONVICT 103
#define JOHN_THE_INSURGENT 104
#define DOROTHY_THE_TIPSY 105
#define STEWARD_ROWLAND 106
#define MARSHAL_CATHERINE 107
#define SOLDIER_LEONARD 108
#define OAK_ORACLE 109
#define SAILOR_TOBIAS 110
#define GYMARA_THE_SAILOR 111
#define THANAS_HOLD_BARTENDER 112
#define DEMON_GUARD 113
#define UMFREY_THE_SPY 114
#define MAGE_MARY_ANN 115
#define HILDA_THE_EXPLORER 116
#define PROSPECTOR_DIVANA 117
#define BRONK_THE_SERVANT 118
#define PASSWORD_SQUARE 119
#define CIRCLE_CONTROL 120
#define THANA_THE_USURPER 121
#define MSWORD_VENDOR 122
#define MBOW_VENDOR 123
#define FULK_THE_DEPARTED 124
#define SIR_DEVON 125
#define RAY_THE_APPRENTICE 126
#define SAM_THE_ADVENTURER 127
#define ROLF_THE_MIGHTY 128

#define NPC_MAX      ROLF_THE_MIGHTY

#define DEFAULT_FUNCTION            0
#define QUEEN_FUNCTION              1
#define VENDOR_FUNCTION             2
// #define GROCER_FUNCTION             2
// #define SLING_VENDOR_FUNCTION       3
// #define LEATHER_VENDOR_FUNCTION     4
#define BARTENDER_FUNCTION          3
// #define HEALER_FUNCTION             6
// #define PLATE_VENDOR_FUNCTION       8
#define RISWYNN_FUNCTION            4
// #define AXE_VENDOR_FUNCTION         10
// #define MACE_VENDOR_FUNCTION        11
// #define BOW_VENDOR_FUNCTION         12
// #define HEALING_POTION_VENDOR_FUNCTION  13
// #define SHIP_VENDOR_FUNCTION        14
// #define SWORD_VENDOR_FUNCTION       15
// #define CHAINMAIL_VENDOR_FUNCTION   16
// #define CURE_POTION_VENDOR_FUNCTION 17
#define MAZINNA_FR_FUNCTION         5
#define JAYLAN_DA_FUNCTION          6
#define WIXA_FUNCTION               7
#define BAXTON_ER_FUNCTION          8
#define ADVANCED_TRAINER_FUNCTION   9
// #define MAXIMILIAN_TRAINER_FUNCTION 9
// #define DURON_TRAINER_FUNCTION      10
// #define GOLDWINE_TRAINER_FUNCTION   11
#define TRAGUT_FUNCTION             10
#define SAMUEL_FUNCTION             11
#define ALDERNEY_FUNCTION           12
#define AVIL_FUNCTION               13
// #define CASTLE_ORACLE_FUNCTION      14
// #define OAK_ORACLE_FUNCTION         15
#define PASSWORD_SQUARE_FUNCTION    14
#define CIRCLE_CONTROL_FUNCTION     15
#define MYSTERIOUS_HERMIT_FUNCTION  16
#define FULK_FUNCTION               17
#define EVIL_PLACE_FUNCTION         18
#define THANA_FUNCTION              19

#endif  // GAMETXT_H
